Added `update-my-replay-wheel-and-jar` and `sync-my-airflow-dags` commands (#46)
* Update replayctl, airflow-worker.dockerfile, experiments/README.md

* Add new commands to replayctl for working with advanced workflow deployment scenarios to Airflow 

---------

Co-authored-by: Azamat G <mr.g.azamat@gmail.com>

diff --git a/experiments/bin/replayctl b/experiments/bin/replayctl
--- a/experiments/bin/replayctl
+++ b/experiments/bin/replayctl
@@ -29,24 +29,21 @@ fi
 
 
 function build_airflow_image() {
-  cp ../LightAutoML/dist/SparkLightAutoML_DEV-0.3.2-py3-none-any.whl .
+  mkdir -p /tmp/replay_airflow_image_files
 
-  cp ../LightAutoML/jars/spark-lightautoml_2.12-0.1.1.jar .
+  cp ../LightAutoML/dist/SparkLightAutoML_DEV-0.3.2-py3-none-any.whl /tmp/replay_airflow_image_files/
 
-  cp experiments/docker/yarn-site.xml yarn-site.xml
+  cp experiments/docker/yarn-site.xml /tmp/replay_airflow_image_files/yarn-site.xml
 
-  cp experiments/docker/core-site.xml core-site.xml
+  cp experiments/docker/core-site.xml /tmp/replay_airflow_image_files/core-site.xml
 
   poetry build
 
-  poetry export --without-hashes -f requirements.txt > requirements.txt
+  poetry export --without-hashes -f requirements.txt > /tmp/replay_airflow_image_files/requirements.txt
 
-  docker build -t node2.bdcl:5000/airflow-worker:latest -f experiments/docker/airflow-worker.dockerfile .
+  docker build -t node2.bdcl:5000/airflow-worker:latest -f experiments/docker/airflow-worker.dockerfile /tmp/replay_airflow_image_files
 
-  rm core-site.xml
-  rm yarn-site.xml
-  rm SparkLightAutoML_DEV-0.3.2-py3-none-any.whl
-  rm spark-lightautoml_2.12-0.1.1.jar
+  rm -r /tmp/replay_airflow_image_files
 }
 
 function push_airflow_image() {
@@ -113,11 +110,42 @@ function build_spark_replay_image() {
 }
 
 function airflow_sync_dags() {
-  rsync -v --perms --chmod=u+rwx,g+rwx,o+rwx experiments/dag_*.py  node2.bdcl:/mnt/ess_storage/DN_1/storage/Airflow/dags
+  if [[ -z "${USERNAME_ON_CLUSTER}" ]]; then
+      SUFFIX=""
+  else
+      SUFFIX="_${USERNAME_ON_CLUSTER}"
+  fi
+
+  rsync -v --perms --chmod=u+rwx,g+rwx,o+rwx experiments/dag_*"${SUFFIX}".py node2.bdcl:/mnt/ess_storage/DN_1/storage/Airflow/dags
 }
 
 function airflow_port_forward() {
     kubectl -n airflow port-forward svc/airflow-webserver 8080:8080
+}
+
+function upd_wheels_and_jars() {
+  if [[ -z "${USERNAME_ON_CLUSTER}" ]]; then
+      SUFFIX=""
+  else
+      SUFFIX="_${USERNAME_ON_CLUSTER}"
+  fi
+
+  echo "building RePlay wheel"
+  poetry build
+
+  SPARK_SUBMIT_FILES_DIR="/mnt/ess_storage/DN_1/storage/SLAMA/kaggle_used_cars_dataset/spark_submit_files/"
+  # copying RePlay wheel and jar files to .../spark_submit_files/ mounted in airflow container
+  scp dist/replay_rec-0.10.0-py3-none-any.whl node2.bdcl:"${SPARK_SUBMIT_FILES_DIR}"replay_rec-0.10.0-py3-none-any"${SUFFIX}".whl
+  scp scala/target/scala-2.12/replay_2.12-0.1.jar node2.bdcl:"${SPARK_SUBMIT_FILES_DIR}"replay_2.12-0.1"${SUFFIX}".jar
+}
+
+function upd_replay_package() {
+  if [[ -z "${USERNAME_ON_CLUSTER}" ]]; then
+      echo "USERNAME_ON_CLUSTER environment variable is required!"
+      exit 1
+  fi
+
+  rsync -avr --perms --chmod=u+rwx,g+rwx,o+rwx replay node2.bdcl:/mnt/ess_storage/DN_1/storage/Airflow/dags/"${USERNAME_ON_CLUSTER}"_packages/
 }
 
 function help() {
@@ -171,6 +199,14 @@ function main () {
 
     "airflow-port-forward")
         airflow_port_forward
+        ;;
+
+    "upd-wheels-and-jars")
+        upd_wheels_and_jars
+        ;;
+
+    "upd-replay-pkg")
+        upd_replay_package
         ;;
 
     *)
